# Generated by Django 4.2.4 on 2023-08-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='_id',
        ),
    ]
